### PR TITLE
Mongo cs

### PR DESCRIPTION
**Pull request by C-Stein**
@sscotth Here's a rough draft of the info in the readme. Starting work now on the exercise. Let me know what you think.

### CODE REVIEW

**Comment by sscotth** [comment]
Let's add more specific instructions for the mongo setup. This is my process:

```bash
sudo mkdir -p /data/db
sudo chown -R `whoami` /data
```

**Comment by sscotth** [comment]
Make sure the brew commands are in lower case: `brew update`

**Comment by sscotth** [comment]
Also, I think the brew should be `brew install mongodb`...

Using just `mongo` is an alias which may not last.

https://docs.mongodb.com/master/tutorial/install-mongodb-on-os-x/#install-the-mongodb-binaries

**Comment by sscotth** [comment]
Also a markdown thing, for inline code simply use a single tick

**Comment by C-Stein** [comment]
@sscotth - All  of your notes should be incorporated now. Let me know what you think

**Pull request merged**
